name: TESTS
on:
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

     # Dotnet Setup
      - name: Dotnet Setup
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      # Replace this whichever way you build your code
      - name: Build & Test dotnet code
        run: |
          dotnet restore
          dotnet build -c Release no-restore
          dotnet test -c Release --no-restore --no-build --loger trx --results-directory ./TestResults
        continue-on-error: true

      # Using the trx-parser action
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.4.0
        id: trx-parser
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
