name: TESTS
on:
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x

      - uses: actions/checkout@v3
      
      # Replace this whichever way you build your code
      - name: Build & Test dotnet code
        run: |
          dotnet restore
          dotnet build -c Release no-restore
          dotnet test -c Release --no-restore --no-build --blame-hang --blame-hang-timeout 60s --logger /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverageAttribute' /p:ExcludeByFile='**/*.g.cs' /p:Include='[Tools]*' /p:SkipAutoProps=true /p:CoverletOutput='./TestResults/'
#        continue-on-error: true

      # Using the trx-parser action
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.4.0
        id: trx-parser
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}